### ISSUE TITLE
Sample app fails to load for euw2 org

### ISSUE THREAD

**Issue by psurma** [PrinceMerluza/purecloud-premium-app#6]
Hi,
After installing this in my org (which happens to be in eu-west-2) the following error occurs and prevents the page from ever loading, after selecting Apps > Premium Client Application Example

```
Uncaught Error: Could not parse 'euw2.pure.cloud' into a known PureCloud environment
    at new ClientApp (purecloud-client-app-sdk.js:2035)
    at setup (main.js:140)
    at main.js:290
```

**Comment by crespino4** [comment]
Thanks for letting us know.  Please check the /docs/wizard/index.html file and verify that it contains the following script tag:

    <script src="https://sdk-cdn.mypurecloud.com/javascript/latest/purecloud-platform-client-v2.min.js"></script>

If you obtained your code prior to Dec 9 2020 then it is possible that it was using the "latest" path and therefore wasn't picking up the new eu-west-2 region that was just recently added to the Genesys Cloud regions.
